### ISSUE TITLE
[Feature]: Include Topic 'Context API and Redux'

### ISSUE THREAD

**Issue by misbahafzal** [Techwards/all-about-react#30]
### Contact Details

misbah.afzal@techwards.co

### Feature Type

New react topic

### Description

We may need resources/blogs/articles/podcasts related to how we can use context api and redux in react, difference between both of them and their uses.

**Comment by nabeel-shakeel** [comment]
@misbahafzal Thanks for opening a feature request, yes indeed its a topic that we need to cover, we have already created a feature request for it, you can pick that #25
