### ISSUE TITLE
[Feature]: Add new topic "React in Typescript"

### ISSUE THREAD

**Issue by nabeel-shakeel** [Techwards/all-about-react#34]
### Feature Type

New react topic

### Description

Add resources and content of _React in Typescript_ from already added react experts, and you can suggest new experts if you find when working on task

**Comment by hamza-akram** [comment]
@nabeel-shakeel I'm interested, can I pick this issue?

**Comment by nabeel-shakeel** [comment]
@hamza-akram: Great! Go ahead
